(*                       Синтаксис языка Mollys                            *)
(* Синтаксис описан согласно стандарту: EBNF (ISO/IEC 14977 Extended BNF). *)


(* Лексические элементы *)
буква           =   "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M"
                  | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
                  | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m"
                  | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z";

десятичная цифра 
                =   "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";

шестнадцатеричная цифра
                =  десятичная цифра | "A" | "B" | "C" | "D" | "E" | "F"
                                    | "a" | "b" | "c" | "d" | "e" | "f";

(* Основные токены *)
идентификатор               = буква, { буква | десятичная цифра | "_" };

целочисленный десятичный литерал
                            = десятичная цифра, { десятичная цифра };

целочисленный шестнадцатеричный литерал
                            =   шестнадцатеричная цифра, { шестнадцатеричная цифра };